"""Ingestion - turn whatever comes out of Cube19/Bullhorn into a Dataset.

Real exports never match a spec. Column names differ per tenant, per report screen and
per person who ran the export. So the loader matches headers loosely, records what it
could not map, and keeps going - a mapping report you can read beats a stack trace on
row 40,000.

Canonical CSV shapes are documented in data/sample/ (generated by
scripts/generate_sample_data.py), which doubles as the format spec to hand whoever runs
the extraction.
"""

from __future__ import annotations

import csv
import json
import re
from dataclasses import dataclass, field
from datetime import date, datetime
from pathlib import Path

from .model import (
    Activity, Client, Consultant, Dataset, Job, Placement, PlacementType, Stage, StageEvent,
)

__all__ = ["DEFAULT_STATUS_MAP", "MappingReport", "load_dataset", "load_status_map", "normalise_stage"]

# Bullhorn ships defaults; every tenant renames them. These are starting guesses only -
# docs/06 item 1.1 says get the real list, and this is why.
DEFAULT_STATUS_MAP: dict[str, str] = {
    # internal shortlist
    "internally submitted": Stage.INTERNAL_SUBMISSION.value,
    "internal submission": Stage.INTERNAL_SUBMISSION.value,
    "shortlisted": Stage.INTERNAL_SUBMISSION.value,
    "new lead": Stage.INTERNAL_SUBMISSION.value,
    # CV sent to client
    "client submission": Stage.CV_SENT.value,
    "submitted to client": Stage.CV_SENT.value,
    "cv sent": Stage.CV_SENT.value,
    "sendout": Stage.CV_SENT.value,
    "sent to client": Stage.CV_SENT.value,
    # interviews
    "interview scheduled": Stage.FIRST_INTERVIEW.value,
    "1st interview": Stage.FIRST_INTERVIEW.value,
    "first interview": Stage.FIRST_INTERVIEW.value,
    "interview": Stage.FIRST_INTERVIEW.value,
    "2nd interview": Stage.FURTHER_INTERVIEW.value,
    "second interview": Stage.FURTHER_INTERVIEW.value,
    "3rd interview": Stage.FURTHER_INTERVIEW.value,
    "further interview": Stage.FURTHER_INTERVIEW.value,
    "final interview": Stage.FURTHER_INTERVIEW.value,
    # end states
    "offer": Stage.OFFER.value,
    "offered": Stage.OFFER.value,
    "offer extended": Stage.OFFER.value,
    "placed": Stage.PLACED.value,
    "placement": Stage.PLACED.value,
    "client declined": Stage.REJECTED.value,
    "candidate rejected": Stage.REJECTED.value,
    "rejected": Stage.REJECTED.value,
    "withdrawn": Stage.REJECTED.value,
}


def load_status_map(path: str | Path | None) -> dict[str, str]:
    """Load a tenant status map (JSON: {"Gentis status": "canonical_stage"}).

    Merged over the defaults, so a partial map is fine.
    """
    mapping = dict(DEFAULT_STATUS_MAP)
    if path and Path(path).exists():
        with open(path, encoding="utf-8") as fh:
            mapping.update({k.strip().lower(): v for k, v in json.load(fh).items()})
    return mapping


def normalise_stage(status: str, mapping: dict[str, str] | None = None) -> Stage | None:
    """Map a tenant status string to a canonical stage. None = unmapped."""
    mapping = mapping or DEFAULT_STATUS_MAP
    key = re.sub(r"\s+", " ", (status or "").strip().lower())
    value = mapping.get(key)
    if value is None:
        return None
    try:
        return Stage(value)
    except ValueError:
        return None


@dataclass
class MappingReport:
    """What the loader understood, and what it did not. Read this before the numbers."""

    files_read: list[str] = field(default_factory=list)
    rows_read: dict[str, int] = field(default_factory=dict)
    rows_skipped: dict[str, int] = field(default_factory=dict)
    unmapped_statuses: dict[str, int] = field(default_factory=dict)
    unmapped_columns: dict[str, list[str]] = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)

    def render(self) -> str:
        lines = ["Ingestion report", "=" * 40]
        for f in self.files_read:
            lines.append(f"  {f}: {self.rows_read.get(f, 0)} rows"
                         + (f" ({self.rows_skipped[f]} skipped)" if self.rows_skipped.get(f) else ""))
        if self.unmapped_statuses:
            lines.append("\nUNMAPPED STATUSES - these rows were dropped from the funnel:")
            for status, n in sorted(self.unmapped_statuses.items(), key=lambda kv: -kv[1]):
                lines.append(f"  {status!r}: {n} rows")
            lines.append("  -> add them to your status map (docs/06 item 1.1)")
        if self.unmapped_columns:
            lines.append("\nUNRECOGNISED COLUMNS (ignored):")
            for f, cols in self.unmapped_columns.items():
                lines.append(f"  {f}: {', '.join(cols)}")
        for w in self.warnings:
            lines.append(f"\nWARNING: {w}")
        return "\n".join(lines)


# Header aliases. Left = canonical field, right = things exports actually call it.
_ALIASES: dict[str, set[str]] = {
    "submission_id": {"submission_id", "submissionid", "jobsubmissionid", "submission"},
    "job_id": {"job_id", "jobid", "joborderid", "job order id", "job"},
    "candidate_id": {"candidate_id", "candidateid", "candidate"},
    "client_id": {"client_id", "clientid", "clientcorporationid", "company_id", "company", "client"},
    "consultant_id": {"consultant_id", "consultantid", "owner", "ownerid", "user", "userid",
                      "recruiter", "sendinguser", "consultant"},
    "market": {"market", "desk", "vertical", "specialism", "specialty", "division", "team",
               "business unit", "sector"},
    "stage": {"stage", "status", "submission_status", "substatus", "current status"},
    "event_date": {"event_date", "date", "statusdate", "datechanged", "datelastmodified",
                   "transition_date", "dateadded"},
    "placement_type": {"placement_type", "type", "employment_type", "perm_contract",
                       "jobtype", "employmenttype"},
    "placement_id": {"placement_id", "placementid", "placement"},
    "start_date": {"start_date", "startdate", "datebegin", "date_begin", "placement_date"},
    "gp": {"gp", "nfi", "fee", "net_fee_income", "grossprofit", "gross_profit", "revenue",
           "margin", "value"},
    "fell_off": {"fell_off", "falloff", "fall_off", "cancelled", "terminated"},
    "date_opened": {"date_opened", "dateadded", "date_added", "job_opened", "opened"},
    "date_closed": {"date_closed", "dateclosed", "closed", "dateend"},
    "exclusive": {"exclusive", "exclusivity", "is_exclusive", "retained"},
    "seniority": {"seniority", "level", "job_level", "grade"},
    "activity_date": {"activity_date", "date", "datebegin", "dateadded"},
    "action": {"action", "activity", "activity_type", "note_action", "type"},
    "count": {"count", "qty", "quantity", "n", "total"},
    "name": {"name", "full_name", "fullname", "client_name", "company_name",
             "consultant_name", "user_name"},
    "end_date": {"end_date", "enddate", "leave_date", "date_left"},
    "geo": {"geo", "country", "region", "location"},
    "industry": {"industry", "sector_industry"},
    "date_added": {"date_added", "dateadded", "created"},
}


def _norm_header(h: str) -> str:
    """Collapse a header to comparable form: lowercase, alphanumerics only.

    'Date Added', 'date_added' and 'dateAdded' all become 'dateadded'. Both headers and
    aliases go through this, so the two sides can never drift apart.
    """
    return re.sub(r"[^a-z0-9]", "", (h or "").strip().lower())


# Aliases normalised once, so lookup is a plain set membership test.
_NORM_ALIASES: dict[str, set[str]] = {
    field_name: {_norm_header(a) for a in aliases}
    for field_name, aliases in _ALIASES.items()
}


def _build_index(headers: list[str], wanted: list[str], report: MappingReport, fname: str) -> dict[str, str]:
    """Map canonical field -> actual header present in this file.

    Exact canonical name wins over an alias, so a file that has both 'date' and
    'event_date' binds event_date rather than whichever came first.
    """
    normalised = [(_norm_header(h), h) for h in headers]
    index: dict[str, str] = {}
    for field_name in wanted:
        aliases = _NORM_ALIASES.get(field_name, {_norm_header(field_name)})
        exact = _norm_header(field_name)
        match = next((orig for norm, orig in normalised if norm == exact), None)
        if match is None:
            match = next((orig for norm, orig in normalised if norm in aliases), None)
        if match is not None:
            index[field_name] = match
    used = set(index.values())
    unmapped = [h for h in headers if h not in used]
    if unmapped:
        report.unmapped_columns[fname] = unmapped
    return index


def _parse_date(value: str) -> date | None:
    if not value:
        return None
    value = value.strip()
    for fmt in ("%Y-%m-%d", "%d/%m/%Y", "%m/%d/%Y", "%Y-%m-%d %H:%M:%S",
                "%d-%m-%Y", "%Y/%m/%d", "%d.%m.%Y"):
        try:
            return datetime.strptime(value[:len(fmt) + 2].strip(), fmt).date()
        except ValueError:
            continue
    try:
        return datetime.fromisoformat(value.replace("Z", "")).date()
    except ValueError:
        return None


def _parse_float(value: str) -> float:
    if value is None:
        return 0.0
    cleaned = re.sub(r"[^0-9.\-]", "", str(value).replace(",", ""))
    try:
        return float(cleaned) if cleaned not in ("", "-", ".") else 0.0
    except ValueError:
        return 0.0


def _parse_bool(value: str) -> bool:
    return str(value).strip().lower() in {"1", "true", "yes", "y", "exclusive", "retained"}


def _parse_ptype(value: str) -> PlacementType:
    v = (value or "").strip().lower()
    if v.startswith(("c", "temp", "interim", "freelance")):
        return PlacementType.CONTRACT
    return PlacementType.PERM


def _read_csv(path: Path) -> tuple[list[str], list[dict]]:
    with open(path, encoding="utf-8-sig", newline="") as fh:
        sample = fh.read(8192)
        fh.seek(0)
        try:
            dialect = csv.Sniffer().sniff(sample, delimiters=",;\t|")
        except csv.Error:
            dialect = csv.excel
        reader = csv.DictReader(fh, dialect=dialect)
        rows = list(reader)
        return (reader.fieldnames or []), rows


def load_dataset(
    path: str | Path,
    status_map_path: str | Path | None = None,
) -> tuple[Dataset, MappingReport]:
    """Load every recognised CSV in ``path`` into a Dataset.

    Recognised by filename stem: stage_events, submissions, placements, jobs,
    activities, consultants, clients. Missing files are fine - the engine degrades
    to whatever bands it has data for, which is what happens in practice when the
    call log turns out to be unusable.
    """
    directory = Path(path)
    report = MappingReport()
    status_map = load_status_map(status_map_path)
    ds = Dataset()

    handlers = {
        ("stage_events", "submissions"): _load_stage_events,
        ("placements",): _load_placements,
        ("jobs",): _load_jobs,
        ("activities", "activity"): _load_activities,
        ("consultants", "users"): _load_consultants,
        ("clients", "companies"): _load_clients,
    }

    for file in sorted(directory.glob("*.csv")):
        stem = file.stem.lower()
        handler = next((h for keys, h in handlers.items() if any(k in stem for k in keys)), None)
        if handler is None:
            report.warnings.append(f"{file.name}: filename not recognised, skipped")
            continue
        headers, rows = _read_csv(file)
        report.files_read.append(file.name)
        report.rows_read[file.name] = len(rows)
        handler(ds, rows, headers, report, file.name, status_map)

    _validate(ds, report)
    return ds, report


def _load_stage_events(ds, rows, headers, report, fname, status_map):
    idx = _build_index(headers, ["submission_id", "job_id", "candidate_id", "client_id",
                                 "consultant_id", "market", "stage", "event_date",
                                 "placement_type"], report, fname)
    skipped = 0
    for i, row in enumerate(rows):
        stage = normalise_stage(row.get(idx.get("stage", ""), ""), status_map)
        when = _parse_date(row.get(idx.get("event_date", ""), ""))
        if stage is None:
            raw = (row.get(idx.get("stage", ""), "") or "").strip()
            report.unmapped_statuses[raw] = report.unmapped_statuses.get(raw, 0) + 1
            skipped += 1
            continue
        if when is None:
            skipped += 1
            continue
        ds.stage_events.append(StageEvent(
            submission_id=row.get(idx.get("submission_id", ""), "") or f"s{i}",
            job_id=row.get(idx.get("job_id", ""), "") or "",
            candidate_id=row.get(idx.get("candidate_id", ""), "") or "",
            client_id=row.get(idx.get("client_id", ""), "") or "",
            consultant_id=row.get(idx.get("consultant_id", ""), "") or "",
            market=row.get(idx.get("market", ""), "") or "Unknown",
            stage=stage,
            event_date=when,
            placement_type=_parse_ptype(row.get(idx.get("placement_type", ""), "")),
        ))
    report.rows_skipped[fname] = skipped


def _load_placements(ds, rows, headers, report, fname, status_map):
    idx = _build_index(headers, ["placement_id", "job_id", "client_id", "consultant_id",
                                 "market", "start_date", "gp", "placement_type",
                                 "fell_off", "submission_id"], report, fname)
    skipped = 0
    for i, row in enumerate(rows):
        when = _parse_date(row.get(idx.get("start_date", ""), ""))
        if when is None:
            skipped += 1
            continue
        ds.placements.append(Placement(
            placement_id=row.get(idx.get("placement_id", ""), "") or f"p{i}",
            job_id=row.get(idx.get("job_id", ""), "") or "",
            client_id=row.get(idx.get("client_id", ""), "") or "",
            consultant_id=row.get(idx.get("consultant_id", ""), "") or "",
            market=row.get(idx.get("market", ""), "") or "Unknown",
            start_date=when,
            gp=_parse_float(row.get(idx.get("gp", ""), "")),
            placement_type=_parse_ptype(row.get(idx.get("placement_type", ""), "")),
            fell_off=_parse_bool(row.get(idx.get("fell_off", ""), "")),
            submission_id=row.get(idx.get("submission_id", ""), "") or None,
        ))
    report.rows_skipped[fname] = skipped


def _load_jobs(ds, rows, headers, report, fname, status_map):
    idx = _build_index(headers, ["job_id", "client_id", "consultant_id", "market",
                                 "date_opened", "date_closed", "exclusive", "seniority",
                                 "placement_type"], report, fname)
    skipped = 0
    for i, row in enumerate(rows):
        when = _parse_date(row.get(idx.get("date_opened", ""), ""))
        if when is None:
            skipped += 1
            continue
        ds.jobs.append(Job(
            job_id=row.get(idx.get("job_id", ""), "") or f"j{i}",
            client_id=row.get(idx.get("client_id", ""), "") or "",
            consultant_id=row.get(idx.get("consultant_id", ""), "") or "",
            market=row.get(idx.get("market", ""), "") or "Unknown",
            date_opened=when,
            date_closed=_parse_date(row.get(idx.get("date_closed", ""), "")),
            exclusive=_parse_bool(row.get(idx.get("exclusive", ""), "")),
            seniority=row.get(idx.get("seniority", ""), "") or "mid",
            placement_type=_parse_ptype(row.get(idx.get("placement_type", ""), "")),
        ))
    report.rows_skipped[fname] = skipped


def _load_activities(ds, rows, headers, report, fname, status_map):
    idx = _build_index(headers, ["activity_date", "consultant_id", "market", "action",
                                 "client_id", "count"], report, fname)
    skipped = 0
    for row in rows:
        when = _parse_date(row.get(idx.get("activity_date", ""), ""))
        if when is None:
            skipped += 1
            continue
        count = _parse_float(row.get(idx.get("count", ""), "")) or 1
        ds.activities.append(Activity(
            activity_date=when,
            consultant_id=row.get(idx.get("consultant_id", ""), "") or "",
            market=row.get(idx.get("market", ""), "") or "Unknown",
            action=(row.get(idx.get("action", ""), "") or "").strip().lower(),
            client_id=row.get(idx.get("client_id", ""), "") or None,
            count=int(count),
        ))
    report.rows_skipped[fname] = skipped


def _load_consultants(ds, rows, headers, report, fname, status_map):
    idx = _build_index(headers, ["consultant_id", "name", "market", "start_date",
                                 "end_date"], report, fname)
    for i, row in enumerate(rows):
        start = _parse_date(row.get(idx.get("start_date", ""), ""))
        if start is None:
            report.warnings.append(
                f"{fname}: consultant without a start date - ramp curves will exclude them")
            start = date(1970, 1, 1)
        ds.consultants.append(Consultant(
            consultant_id=row.get(idx.get("consultant_id", ""), "") or f"c{i}",
            name=row.get(idx.get("name", ""), "") or "",
            market=row.get(idx.get("market", ""), "") or "Unknown",
            start_date=start,
            end_date=_parse_date(row.get(idx.get("end_date", ""), "")),
        ))


def _load_clients(ds, rows, headers, report, fname, status_map):
    idx = _build_index(headers, ["client_id", "name", "market", "geo", "date_added",
                                 "industry"], report, fname)
    for i, row in enumerate(rows):
        ds.clients.append(Client(
            client_id=row.get(idx.get("client_id", ""), "") or f"cl{i}",
            name=row.get(idx.get("name", ""), "") or "",
            market=row.get(idx.get("market", ""), "") or "Unknown",
            geo=row.get(idx.get("geo", ""), "") or "BE",
            date_added=_parse_date(row.get(idx.get("date_added", ""), "")),
            industry=row.get(idx.get("industry", ""), "") or "",
        ))


def _validate(ds: Dataset, report: MappingReport) -> None:
    """Checks worth running before anyone reads a number off this."""
    if ds.stage_events and not any(e.stage is Stage.CV_SENT for e in ds.stage_events):
        report.warnings.append(
            "No CV-sent events found. The status map almost certainly does not match this "
            "tenant - every delivery ratio will be wrong. Fix the map before proceeding.")
    if ds.placements and not ds.consultants:
        report.warnings.append(
            "No consultant file: per-head and ramp analysis unavailable (docs/06 item 3.6).")
    if ds.placements and not ds.jobs:
        report.warnings.append("No job file: fill rate and CVs-per-job unavailable.")
    if not ds.activities:
        report.warnings.append(
            "No activity data: Band-1 BD ratios unavailable. Anchor targets at CVs sent "
            "instead (docs/04 section 3).")
    zero_gp = sum(1 for p in ds.placements if p.gp <= 0)
    if ds.placements and zero_gp / len(ds.placements) > 0.1:
        report.warnings.append(
            f"{zero_gp}/{len(ds.placements)} placements have zero GP - check the fee column "
            "mapping and the perm/contract GP rules (docs/06 item 1.5).")
